"""Report formatters — export an :class:`IncidentReport` to Markdown, JSON, PDF.

The formatters are pure functions over :class:`IncidentReport` and return
strings or bytes so the caller decides how to persist or download the output
(the API layer can stream the bytes to a client). No files are written here.
"""

from __future__ import annotations

import io
import json
from typing import Any

from app.reports.models import IncidentReport, ReportFormat


def to_markdown(report: IncidentReport) -> str:
    """Serialize an :class:`IncidentReport` to Markdown text."""
    lines: list[str] = []

    lines.append(f"# {report.incident_title}")
    lines.append("")
    lines.append(f"**Severity:** {report.severity.value}")
    lines.append(f"**Report ID:** {report.report_id}")
    lines.append(f"**Generated:** {report.generated_at.isoformat()}")
    lines.append(f"**Generated by:** {report.generated_by}")
    lines.append(f"**Version:** {report.report_version}")
    lines.append("")

    if report.executive_summary:
        lines.append("## Executive Summary")
        lines.append("")
        lines.append(report.executive_summary)
        lines.append("")

    if report.timeline:
        lines.append("## Timeline")
        lines.append("")
        for event in report.timeline:
            lines.append(f"- **{event.timestamp}** — {event.description}")
        lines.append("")

    if report.affected_assets:
        lines.append("## Affected Assets")
        lines.append("")
        for asset in report.affected_assets:
            detail = f" ({asset.detail})" if asset.detail else ""
            lines.append(f"- {asset.value} ({asset.asset_type}){detail}")
        lines.append("")

    if report.iocs:
        lines.append("## Indicators of Compromise")
        lines.append("")
        for ioc in report.iocs:
            lines.append(f"- {ioc.value} ({ioc.indicator_type})")
        lines.append("")

    if report.mitre_mapping.get("techniques"):
        lines.append("## MITRE ATT&CK Mapping")
        lines.append("")
        for technique in report.mitre_mapping["techniques"]:
            if isinstance(technique, dict):
                lines.append(
                    f"- **{technique.get('technique_id', '')}** "
                    f"{technique.get('name', '')} — {technique.get('tactic', '')}"
                )
        lines.append("")

    if report.nmap_findings:
        lines.append("## Nmap Findings")
        lines.append("")
        for finding in report.nmap_findings:
            lines.append(_dict_block(finding))
        lines.append("")

    if report.virustotal_findings:
        lines.append("## VirusTotal Findings")
        lines.append("")
        for finding in report.virustotal_findings:
            lines.append(_dict_block(finding))
        lines.append("")

    if report.shodan_findings:
        lines.append("## Shodan Findings")
        lines.append("")
        for finding in report.shodan_findings:
            lines.append(_dict_block(finding))
        lines.append("")

    if report.wazuh_alerts:
        lines.append("## Wazuh Alerts")
        lines.append("")
        for alert in report.wazuh_alerts:
            lines.append(_dict_block(alert))
        lines.append("")

    lines.append("## Risk Assessment")
    lines.append("")
    lines.append(f"- **Likelihood:** {report.risk_assessment.likelihood}")
    lines.append(f"- **Impact:** {report.risk_assessment.impact}")
    lines.append(f"- **Score:** {report.risk_assessment.score}")
    lines.append("")

    if report.recommendations:
        lines.append("## Recommendations")
        lines.append("")
        for rec in report.recommendations:
            lines.append(f"- {rec}")
        lines.append("")

    if report.analyst_notes:
        lines.append("## Analyst Notes")
        lines.append("")
        for note in report.analyst_notes:
            lines.append(f"- {note}")
        lines.append("")

    if report.rag_context:
        lines.append("## RAG Context")
        lines.append("")
        for item in report.rag_context:
            lines.append(_dict_block(item))
        lines.append("")

    return "\n".join(lines).strip() + "\n"


def to_json(report: IncidentReport) -> str:
    """Serialize an :class:`IncidentReport` to a JSON string."""
    return json.dumps(report.to_dict(), indent=2, sort_keys=False)


def to_pdf(report: IncidentReport) -> bytes:
    """Render an :class:`IncidentReport` to a PDF and return the bytes."""
    from reportlab.lib import colors
    from reportlab.lib.pagesizes import A4
    from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
    from reportlab.lib.units import mm
    from reportlab.platypus import (
        Paragraph,
        SimpleDocTemplate,
        Spacer,
        Table,
        TableStyle,
    )

    buffer = io.BytesIO()
    doc = SimpleDocTemplate(
        buffer,
        pagesize=A4,
        rightMargin=18 * mm,
        leftMargin=18 * mm,
        topMargin=18 * mm,
        bottomMargin=18 * mm,
    )
    styles = getSampleStyleSheet()
    title_style = ParagraphStyle(
        "ReportTitle",
        parent=styles["Title"],
        spaceAfter=6,
    )
    heading_style = ParagraphStyle(
        "ReportHeading",
        parent=styles["Heading2"],
        spaceBefore=10,
        spaceAfter=4,
    )
    body_style = ParagraphStyle(
        "ReportBody",
        parent=styles["BodyText"],
        spaceAfter=4,
    )

    flow: list[Any] = []
    flow.append(Paragraph(report.incident_title, title_style))
    flow.append(Paragraph(f"<b>Severity:</b> {report.severity.value}", body_style))
    flow.append(Paragraph(f"<b>Report ID:</b> {report.report_id}", body_style))
    flow.append(Paragraph(f"<b>Generated:</b> {report.generated_at.isoformat()}", body_style))
    flow.append(Paragraph(f"<b>Generated by:</b> {report.generated_by}", body_style))
    flow.append(Spacer(1, 6))

    if report.executive_summary:
        flow.append(Paragraph("Executive Summary", heading_style))
        flow.append(Paragraph(_escape(report.executive_summary), body_style))

    if report.affected_assets:
        flow.append(Paragraph("Affected Assets", heading_style))
        rows: list[list[str]] = [["Asset", "Type", "Detail"]]
        for asset in report.affected_assets:
            rows.append([asset.value, asset.asset_type, asset.detail])
        flow.append(_table(rows, Paragraph, Table, TableStyle, colors, styles))

    if report.iocs:
        flow.append(Paragraph("Indicators of Compromise", heading_style))
        rows = [["Value", "Type"]]
        for ioc in report.iocs:
            rows.append([ioc.value, ioc.indicator_type])
        flow.append(_table(rows, Paragraph, Table, TableStyle, colors, styles))

    if report.mitre_mapping.get("techniques"):
        flow.append(Paragraph("MITRE ATT&CK Mapping", heading_style))
        rows = [["ID", "Name", "Tactic"]]
        for technique in report.mitre_mapping["techniques"]:
            if isinstance(technique, dict):
                rows.append(
                    [
                        str(technique.get("technique_id", "")),
                        str(technique.get("name", "")),
                        str(technique.get("tactic", "")),
                    ]
                )
        flow.append(_table(rows, Paragraph, Table, TableStyle, colors, styles))

    if report.recommendations:
        flow.append(Paragraph("Recommendations", heading_style))
        for rec in report.recommendations:
            flow.append(Paragraph(f"&#8226; {_escape(rec)}", body_style))

    flow.append(Spacer(1, 6))
    flow.append(Paragraph("Risk Assessment", heading_style))
    flow.append(
        Paragraph(
            f"<b>Likelihood:</b> {report.risk_assessment.likelihood} &nbsp;|&nbsp; "
            f"<b>Impact:</b> {report.risk_assessment.impact} &nbsp;|&nbsp; "
            f"<b>Score:</b> {report.risk_assessment.score}",
            body_style,
        )
    )

    doc.build(flow)
    return buffer.getvalue()


def _table(
    rows: list[list[str]],
    paragraph_cls: Any,
    table_cls: Any,
    table_style_cls: Any,
    colors_mod: Any,
    styles: Any,
) -> Any:
    """Build a styled reportlab table from string rows.

    The reportlab classes and the stylesheet are passed in so this helper
    stays import-free and trivially testable without a live reportlab import
    at module scope.
    """
    body_style = styles["BodyText"]
    data = [
        [
            paragraph_cls(_escape(cell), body_style)
            for cell in row
        ]
        for row in rows
    ]
    table = table_cls(data)
    table.setStyle(
        table_style_cls(
            [
                ("BACKGROUND", (0, 0), (-1, 0), colors_mod.HexColor("#1f2937")),
                ("TEXTCOLOR", (0, 0), (-1, 0), colors_mod.white),
                ("GRID", (0, 0), (-1, -1), 0.5, colors_mod.grey),
                ("VALIGN", (0, 0), (-1, -1), "TOP"),
                ("LEFTPADDING", (0, 0), (-1, -1), 4),
                ("RIGHTPADDING", (0, 0), (-1, -1), 4),
                ("TOPPADDING", (0, 0), (-1, -1), 3),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 3),
            ]
        )
    )
    return table


def _escape(text: str) -> str:
    """Escape XML-significant characters for ReportLab paragraphs."""
    return (
        str(text)
        .replace("&", "&amp;")
        .replace("<", "<")
        .replace(">", ">")
    )


def _dict_block(data: dict[str, Any]) -> str:
    """Render a dict as a compact Markdown code block."""
    return f"```json\n{json.dumps(data, indent=2, default=str)}\n```"


def format_report(report: IncidentReport, fmt: ReportFormat) -> str | bytes:
    """Dispatch to the requested formatter.

    :param report: The report to format.
    :param fmt: One of :class:`ReportFormat`.
    :returns: Markdown/JSON string, or PDF bytes.
    """
    if fmt == ReportFormat.MARKDOWN:
        return to_markdown(report)
    if fmt == ReportFormat.JSON:
        return to_json(report)
    if fmt == ReportFormat.PDF:
        return to_pdf(report)
    raise ValueError(f"Unsupported report format: {fmt}")


__all__ = [
    "format_report",
    "to_json",
    "to_markdown",
    "to_pdf",
]
